
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: eds-webhook
webhooks:
  - name: eds-webhook.vzw.com
    clientConfig:
      service:
        name: eds-webhook
        namespace: default
        path: "/service"
      caBundle: "${CA_BUNDLE}"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["services"]
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
