apiVersion: v1
kind: ServiceAccount
metadata:
  name: eds-serviceaccount
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: eds-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods","services","namespaces","deployments","jobs","configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eds-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: eds-serviceaccount # name of your service account
  namespace: default # this is the namespace your service account is in
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: eds-clusterrole
  apiGroup: rbac.authorization.k8s.io