import vzEdgeDiscovery, random, json, requests, sys, argparse

# Create arg parser to enable following syntax: python3 edsSetup.py --carrier_ips $carrier_ips --wlzs $wlzs
parser = argparse.ArgumentParser(description='EDS configuration')
parser.add_argument('--carrier_ips', action="store", dest='carrier_ips', default = "")
parser.add_argument('--wlzs', action="store", dest='wlzs', default = "")
args = parser.parse_args()

"""
Step 0: Filter input to create variables for service endpoints
"""
carrier_ip_addresses=args.carrier_ips.split("\t")
wavelength_zones=args.wlzs.split("\t")
fqdns=[]

print(carrier_ip_addresses)
print(wavelength_zones)

for w in wavelength_zones:
    fqdns.append(str(w[14:16])+"application.service.com")


"""
Step 1: Authenticate to Verizon Edge Discovery Service
"""
access_token=vzEdgeDiscovery.authenticate(
    appKey="<your-key>",
    secretKey="<your-secret-key>")

"""
Step 2: Generate Service Profile
"""
serviceProfileId=vzEdgeDiscovery.createServiceProfile(
    accessToken=access_token,
    maxLatency=40)


"""
Step 3: Create Service Registry
"""
myApplicationId="Verizon_5G_Edge_Application"
myServiceEndpointsId=vzEdgeDiscovery.createServiceRegistry(
    accessToken=access_token,
    serviceProfileId=serviceProfileId,
    carrierIps=carrier_ip_addresses,
    availabilityZones=wavelength_zones,
    fqdns=fqdns,
    applicationId=myApplicationId)


## Choose appropriate wait time
import time
time.sleep(120)

"""
Step 7: Delete Service Registry
"""
vzEdgeDiscovery.deleteServiceRegistry(accessToken=access_token,serviceEndpointsId=myServiceEndpointsId)


"""
Step 8: Delete Service Profile

Inputs
    ----------
    accessToken : str
        Authorization bearer token generated by the authenticate() method

    serviceProfileId : str
        The service profile ID being associated with the service endpoint

"""
vzEdgeDiscovery.deleteServiceProfile(accessToken=access_token,serviceProfileId=serviceProfileId)
##########################################################################################################################################
