from vz_edge_discovery import VzEdgeDiscovery
import random
import os

from dotenv import load_dotenv
from pathlib import Path

dotenv_path = Path('resources/.env')
load_dotenv(dotenv_path=dotenv_path)

my_obj = VzEdgeDiscovery()

##########################################################################################################################################

"""
Step 1: Authenticate to Edge discovery service

Inputs
    ----------
    app_key : str
        Application Key generated from the 5G Edge Developer Portal: https://www.verizon.com/business/5g-edge-portal/index.html

    secret_key : str
        Secret Key generated from the 5G Edge Developer Portal: https://www.verizon.com/business/5g-edge-portal/index.html

Outputs
    ----------
    access_token : str
        The response will contain an access_token property that you must include as the authorization bearer token in the header of all API requests.
        The token will be valid for one hour from when it was first issued and any further token requests during that time will return the same token.

"""
app_key=os.getenv('APP_KEY')
secret_key=os.getenv('SECRET_KEY')
access_token=my_obj.authenticate(app_key=app_key,secret_key=secret_key)


"""
Step 2: Generate Service Profile

Inputs
    ----------
    access_token : str
        Authorization bearer token generated by the authenticate() method

    max_latency : str
        The maximum allowable data latency for the application, measured in milliseconds

Outputs
    ----------
    service_profile_id : str
        The service profile ID being associated with the service endpoint. This will be critical when creating your service registry with edge endpoints using the createServiceRegistry() method

"""
service_profile_id=my_obj.create_service_profile(access_token=access_token,max_latency=40)


"""
Step 3 (OPTIONAL): Update Service Profile

Inputs
    ----------
    access_token : str
        Authorization bearer token generated by the authenticate() method

    max_latency : str
        The maximum allowable data latency for the application, measured in milliseconds

    service_profile_id : str
        The service profile ID being associated with the service endpoint

Outputs
    ----------
    service_profile_id : str
        The service profile ID being associated with the service endpoint. This will be critical when creating your service registry with edge endpoints using the createServiceRegistry() method

"""
updated_service_profile_id=my_obj.update_service_profile(access_token=access_token,max_latency=50,service_profile_id=service_profile_id)


"""
Step 4: Create Service Registry

Inputs
    ----------
    access_token : str
        Authorization bearer token generated by the authenticate() method

    service_profile_id : str
        The service profile ID being associated with the service endpoint

    carrier_ips : list
        List of Carrier IP addresses (of type str), in order, to associate to service registry

    availability_zones : list
        List of Availability Zone IDs (of type str), in order, to associate to service registry. Note that len(carrier_ips)==len(availability_zones)

    application_id : str
        The assigned name of the application hosted that will be using the service endpoint

Outputs
    ----------
    service_endpoints_id : str
        A unique identifier for a service endpoint

"""
my_application_id=["APPLICATION_END_POINT_ID_"+str(random.randint(0,10000)), "APPLICATION_END_POINT_ID2_"+str(random.randint(0,10000)), "APPLICATION_END_POINT_ID3_"+str(random.randint(0,10000))] #Create random applicationID to associate to service registry (optional)
my_service_endpoints_id=my_obj.create_service_registry(access_token=access_token,service_profile_id=updated_service_profile_id,carrier_ips=["155.146.0.225","155.146.65.19","155.146.65.19"],availability_zones=["us-east-1-wl1-bos-wlz-1","us-east-1-wl1-nyc-wlz-1","us-east-1-wl1-was-wlz-1"],application_id=my_application_id,fqdns=["verizon.com","verizon.com","verizon.com"])


"""
Step 5: Discover Optimal Endpoints

Inputs
    ----------
    access_token : str
        Authorization bearer token generated by the authenticate() method

    service_endpoints_id : str
        A unique identifier for a service endpoint

    ue_identity : str
        IPv4 address of your mobile client

Outputs
    ----------
    closest_edge_zone : str
        AWS Availability Zone ID corresponding to the optimal the 5G Edge endpoint

    closest_ip : str
        Carrier IP address corresponding to the optimal 5G Edge endpoint

"""
closest_zone=my_obj.discover_closest_edge_zone(access_token=access_token,service_endpoints_id=my_service_endpoints_id,ue_identity="174.249.33.62")


"""
Step 6 (OPTIONAL): Modify Service Registry to Reflect Application Endpoint Change

Inputs
    ----------
    access_token : str
        Authorization bearer token generated by the authenticate() method

    service_profile_id : str
        The service profile ID being associated with the service endpoint

    carrier_ips : list
        List of Carrier IP addresses (of type str), in order, to associate to service registry

    availability_zones : list
        List of Availability Zone IDs (of type str), in order, to associate to service registry. Note that len(carrier_ips)==len(availability_zones)

    application_id : str
        The assigned name of the application hosted that will be using the service endpoint

Outputs
    ----------
    service_endpoints_id : str
        A unique identifier for a service endpoint

"""
my_service_endpoints_id=my_obj.update_service_registry(access_token=access_token,service_endpoints_id=my_service_endpoints_id,carrier_ips=["155.146.11.58","155.146.65.19","155.146.65.19"],availability_zones=["us-east-1-wl1-bos-wlz-1","us-east-1-wl1-nyc-wlz-1","us-east-1-wl1-was-wlz-1"],application_id=my_application_id,service_profile_id=updated_service_profile_id)
closest_zone=my_obj.discover_closest_edge_zone(access_token=access_token,service_endpoints_id=my_service_endpoints_id,ue_identity="174.249.33.62")


"""
Step 7: Delete Service Registry

Inputs
    ----------
    access_token : str
        Authorization bearer token generated by the authenticate() method

    service_endpoints_id : str
        A unique identifier for a service endpoint

"""
my_obj.delete_service_registry(access_token=access_token,service_endpoints_id=my_service_endpoints_id)


"""
Step 8: Delete Service Profile

Inputs
    ----------
    access_token : str
        Authorization bearer token generated by the authenticate() method

    serviceProfileId : str
        The service profile ID being associated with the service endpoint

"""
my_obj.delete_service_profile(access_token=access_token,service_profile_id=updated_service_profile_id)
##########################################################################################################################################
